Issue 81
MobileApps-Cascadia/campus-guidebook-android pull request #93
Opened 2022-02-24 03:22 UTC by odjuliarso

2022-02-24 05:27 UTC, gomezfox requested changes
Copy over in the rest of the xml from develop/fragment_home, and you're golden!

2022-02-24 05:27 UTC, gomezfox commented on app/src/main/res/layout/fragment_home.xml
> -            android:id="@+id/cardView_home_UNUSED4"
From here down, replace the contents of this file with the one from develop to prevent reverting changes already merged into develop

2022-02-24 06:54 UTC, gomezfox approved these changes
Good work!

2022-02-25 01:43 UTC, haythamodeh approved these changes

2022-02-26 02:48 UTC, isaakwheeler approved these changes

2022-02-26 17:19 UTC, Bansenauer-Cascadia commented
@odjuliarso congrats, you're pull request is ready to merge. Please use the GitHub "big green button" on the pull request page to merge it, delete your branch and then close your issue

2022-02-26 19:17 UTC, merged